# @package _global_

defaults:
  - _self_
  - datamodule: mesh_dataset
  - model: cardiac_latent_ode
  - trainer: trainer
  - paths: default

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# configure hydra paths
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
  job_logging:
    handlers:
      file:
        filename: /dev/null
    root:
      handlers: [console]
